console.log(1 + 2);
let num = 1;
console.log(num);
num = num + 2;
console.log(num);
num = num - 1;
console.log(num);
num = num * 2;
console.log(num);
num = num / 3;
console.log(num);
num = 3;
num = num ** 3;
console.log(num);
num = 9;
num = num % 2; // modulo
console.log(num);
num +=2;
num -=2;
num *=2;
num /=2;
num **=2;
num %=2;
console.log(num);
num++;
console.log(num);
num--;
console.log(num);
num = Math.sqrt(9);
console.log(num);
